Allow PlpProgram Creation With a Directory
Progressive-Learning-Platform/PLPAssembler pull request #7
Opened 2020-09-06 05:16 UTC by harsha-kadekar

Any PlpProgram creation needs a directory inside which all the asm files will be present.
Still to do - if the directory already exists, read all the asm files present in that directory and create corresponding PlpFiles

2020-09-06 18:25 UTC, tobielf requested changes

2020-09-06 18:25 UTC, tobielf commented on src/main/java/org/plp/implementations/plpisa/PlpProgram.java
> +public class PlpProgram implements AsmProgram {
Comment the purpose of this class? 
Like 
/** @brief Any PlpProgram creation needs a directory inside which all the asm files will be present.
 *   And all asm files within the given directory will be loaded to memory during object creation.
 */

2020-09-06 18:25 UTC, tobielf commented on src/main/java/org/plp/implementations/plpisa/PlpProgram.java
> +    private void init() throws IOException {
```
private void validatePath throws IOException {
    if(!Files.exists(programDirectory)) {
        Files.createDirectories(programDirectory);
    } else if(!Files.isDirectory(programDirectory)) {
        throw new IOException("Path provided has a file instead of directory - " + programDirectory.toString());
    }
}

private void loadFilesToMemory() throws IOException {
    //ToDo
}
```

2020-09-06 18:25 UTC, tobielf commented on src/main/java/org/plp/implementations/plpisa/PlpProgram.java
> +    public PlpProgram(Path programDirectory) throws IOException{
```
public PlpProgram(Path programDirectory) throws IOException{
    **validatePath(programDirectory);**
    this.programDirectory = programDirectory;
    filesInProgram = new HashMap<>();
    loadFilesToMemory();
}
```

2020-09-06 18:25 UTC, tobielf commented on src/main/java/org/plp/implementations/plpisa/PlpProgram.java
> +    public PlpProgram(Path programDirectory) throws IOException{
I think if we validate the directory before assign to **this.programDirector**y will be easier to understand?
Once we assign we only assign valid value. Later this value is "read-only".

2020-09-06 18:25 UTC, tobielf commented on src/main/java/org/plp/implementations/plpisa/PlpProgram.java
> +    private void init() throws IOException {
So init can break to two smaller specific operations.

validatePath and loadFiles

For now, we only need to test "validatePath", and once it tested and submitted, we are not changing it.

Test cases will be "test valid", "test invalid (exist, not directory)".

2020-09-10 06:38 UTC, harsha-kadekar commented on src/main/java/org/plp/implementations/plpisa/PlpProgram.java
> +public class PlpProgram implements AsmProgram {
Yes going to add it

2020-09-10 06:41 UTC, harsha-kadekar commented on src/main/java/org/plp/implementations/plpisa/PlpProgram.java
> +    private void init() throws IOException {
sounds good. I will update it.

2020-09-10 06:48 UTC, harsha-kadekar commented on src/main/java/org/plp/implementations/plpisa/PlpProgram.java
> +    public PlpProgram(Path programDirectory) throws IOException{
yeah sounds good.

2020-09-11 07:01 UTC, tobielf approved these changes
LGTM!

I think we can throw an "unimplemented" exception for the ToDo functions.

2020-09-12 05:38 UTC, merged